OOP school library: add basic UI
vflorin1995/OOP_school_library pull request #4
Opened 2022-12-22 15:54 UTC by vflorin1995

### Changes

- Add basic UI
- Add Main class

2022-12-22 16:45 UTC, BenMukebo requested changes
### Hi @vflorin1995,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Professional README ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 16:45 UTC, BenMukebo commented on main.rb
> +main
- [ ] The `main.rb` file is the entry point that is invoked at the end of the file. You should Present the user with a list of options to perform here and not in the app.js file.
- This method should do and look similar to the following:

```ruby
def main
  app = App.new()

  response = nil

  puts "Welcome to School Library App!\n\n"
  while response != "7"
    puts "Please choose an option by enterin a number:"
    puts "1 - List all books"
    puts "2 - List all people"
    puts "3 - Create a person"
    puts "4 - Create a book"
    puts "5 - Create a rental"
    puts "6 - List all rentals for a given person id"
    puts "7 - Exit"
    response = gets.chomp

    case response
    when "1"
      app.list_books()
    when "2"
      app.list_people()
    when "3"
      app.create_person()
       ...
    when "7"
      # *Have a way to quit the app.
      puts "Thank you for using this app!"
    end

    puts "\n"
  end
end

main()
```

2022-12-22 16:45 UTC, BenMukebo commented on app.rb
> +  end
- [ ] This should be `class App` and not the `class Main` 🤔

2022-12-22 16:45 UTC, BenMukebo commented on app.rb
> +    end
- [ ] The school library console app should behave in the same way as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) provided for you. But the ` list_all_rentals` option does not work as expected, this is the screenshot 👇🏻 The book title and author does not show correctly, Kindly fix this 👍🏻 



- Your console:

![Screenshot from 2022-12-22 18-14-43](https://user-images.githubusercontent.com/79058364/209180897-175c7498-6bf3-4005-a611-75d57d195a6f.png)


- Video provided:

![Screenshot (1)](https://user-images.githubusercontent.com/79058364/209179860-bf2a4a70-580e-4317-b8b3-59f7df1a9bb6.png)

2022-12-23 08:56 UTC, roshan-bajgain approved these changes
Hi @vflorin1995, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 09:00 UTC, merged